name: camera_info
description: A federated plugin to get camera hardware information (focal length, field of view, base zoom)
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera_info_platform_interface:
    path: ./platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0